-- ---
-- name: haskell_monad_transformer
-- description: Haskell Monad 转换器
-- tags: [haskell, monad, transformer]
-- command_template: runhaskell {filepath} --input {data}
-- args:
--   data:
--     type: string
--     description: 输入数据
--     required: true
-- ---
main = putStrLn "Haskell Monad Transformer"
