-- ---
-- name: sql_query_builder
-- description: SQL 查询构建器
-- tags: [sql, query, builder]
-- command_template: psql -f {filepath} --table {table_name}
-- args:
--   table_name:
--     type: string
--     description: 表名
--     required: true
-- ---
SELECT * FROM users;
